// Country list
export const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See (Vatican City)",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
export type TCountry = (typeof countryList)[number];

// Gender options
export const genderOptions = ["Male", "Female", "Other"] as const;
export type TGender = (typeof genderOptions)[number];

// Availability options
export const availabilityOptions = ["Now", "Soon", "Later"] as const;
export type TAvailability = (typeof availabilityOptions)[number];

// Office Staff Position options
export const officeStaffPositionOptions = [
  "Administrative Director",
  "Community Manager",
  "Data Analyst",
  "Digital Marketing",
  "Medical Staff",
  "Performance Staff",
  "Equipment Staff",
  "Sales",
] as const;
export type TOfficeStaffPosition = (typeof officeStaffPositionOptions)[number];

// Field Staff Position options
export const fieldStaffPositionOptions = [
  "Head Coach",
  "Assistant Coach",
  "GK Coach",
  "Mental Coach",
  "Video Analyst Coach",
  "Specific Offensive Coach",
  "Specific Defensive Coach",
  "Specific Technical Coach",
  "Scout",
  "Technical Director",
  "Academy Director",
  "Director of Coaching",
] as const;
export type TFieldStaffPosition = (typeof fieldStaffPositionOptions)[number];

// Player Position options
export const playerPositionOptions = [
  "GK",
  "Central back",
  "Left back",
  "Right back",
  "Defensive midfielder",
  "Offensive midfielder",
  "Right winger",
  "Left winger",
  "Forward",
  "Striker",
] as const;
export type TPlayerPosition = (typeof playerPositionOptions)[number];

// National Team Category options
export const nationalTeamCategoryOptions = [
  "U14",
  "U15",
  "U16",
  "U17",
  "U18",
  "U19",
  "U20",
  "U21",
] as const;
export type TNationalTeamCategory =
  (typeof nationalTeamCategoryOptions)[number];

// Foot options
export const footOptions = ["Right", "Left", "Both"] as const;
export type TFoot = (typeof footOptions)[number];

// Height Unit options
export const heightUnitOptions = ["cm", "m", "in", "ft"] as const;
export type THeightUnit = (typeof heightUnitOptions)[number];

// Weight Unit options
export const weightUnitOptions = ["kg", "lb"] as const;
export type TWeightUnit = (typeof weightUnitOptions)[number];

// Division Level options
export const divisionLevelOptions = ["1", "2", "3", "4"] as const;
export type TDivisionLevel = (typeof divisionLevelOptions)[number];
